services:
  web:
    build: docker/web
    volumes:
      - .:/var/www
    ports:
      - '${FORWARD_APP_PORT:-8080}:80'
    networks:
      - craft
    depends_on:
      - pgsql
  php:
    build: docker/php
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    volumes:
      - .:/var/www
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    networks:
      - craft
  pgsql:
    image: postgres:15
    ports:
      - '${FORWARD_CRAFT_DB_PORT:-5433}:5432'
    environment:
      PGPASSWORD: '${CRAFT_DB_PASSWORD:-secret}'
      POSTGRES_DB: '${CRAFT_DB_DATABASE}'
      POSTGRES_USER: '${CRAFT_DB_USER}'
      POSTGRES_PASSWORD: '${CRAFT_DB_PASSWORD:-secret}'
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - craft
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${CRAFT_DB_DATABASE}', '-U', '${CRAFT_DB_USER}']
networks:
  craft:
    driver: bridge
volumes:
  db:
    driver: local
