field: 9ad7232b-940b-4762-85a7-0d9081a79992
fieldLayouts:
  c37f415e-fb83-44b2-b232-23bb21d36f6a:
    tabs:
      -
        elements:
          -
            fieldUid: 98aaca2e-1c0f-4ccd-af4b-9b73eed2d996
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7fe4323d-68da-4635-ade2-4f4a83cf1a4e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7fe4323d-68da-4635-ade2-4f4a83cf1a4e:
    contentColumnType: string
    fieldGroup: null
    handle: imageRight
    instructions: ''
    name: 'Image Right'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  98aaca2e-1c0f-4ccd-af4b-9b73eed2d996:
    contentColumnType: string
    fieldGroup: null
    handle: imageLeft
    instructions: ''
    name: 'Image Left'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: dualImageBlock
name: 'Dual Image Block'
sortOrder: 7
