field: 7ff23fb3-f048-4304-a224-ca8dc68a9059
fieldLayouts:
  3b46dc73-6df0-4509-9314-23dd2f59daf1:
    tabs:
      -
        fields:
          15c0650f-bb55-4417-8cff-1fc858828dd5:
            required: false
            sortOrder: 2
          44c7da66-ab2d-4206-b5c0-84dee379f920:
            required: true
            sortOrder: 3
          821fbfea-e5af-4fa8-b6b1-fb5e394dfdfc:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  15c0650f-bb55-4417-8cff-1fc858828dd5:
    contentColumnType: text
    fieldGroup: null
    handle: href
    instructions: ''
    name: Href
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  44c7da66-ab2d-4206-b5c0-84dee379f920:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  821fbfea-e5af-4fa8-b6b1-fb5e394dfdfc:
    contentColumnType: string
    fieldGroup: null
    handle: page
    instructions: ''
    name: Page
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources:
        - 'section:49f87acd-c335-4a0e-9893-36a2f495e2aa'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: link
name: Link
sortOrder: 1
