field: 9ad7232b-940b-4762-85a7-0d9081a79992 # Content Matrix
fieldLayouts:
  48e3561c-cac4-43df-94c9-ce27a33442a0:
    tabs:
      -
        elements:
          -
            fieldUid: e5d85094-e996-4468-9e60-f67f4474a8e1 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e5d85094-e996-4468-9e60-f67f4474a8e1: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textBlock
name: 'Text Block'
sortOrder: 8
