contentColumnType: text
fieldGroup: 713fa806-5df3-45bb-b7c8-6bebe1439715
handle: metaTitle
instructions: ''
name: 'Meta Title'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
