contentColumnType: boolean
fieldGroup: 713fa806-5df3-45bb-b7c8-6bebe1439715
handle: noIndex
instructions: ''
name: 'No Index'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
